/*
 * TaskMate Project
 * (c) 2025 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file parseTag.c
 * @brief autoCode parseTag implementation.
 *
 */

#include "parseTag.h"

#include "fileUtility.h"
#include "tokenizer.h"

typedef struct
{
	const modules_database_t *data_base;
	FILE *file;
	const error_catalog_t *errors;
	const options_list_t *auto_options;
} parseTag_t;

static void writeRunlevelDefine(const parseTag_t *parse);
static void writeModulesCount(const parseTag_t *parse);
static void writeInfo(const parseTag_t *parse);
static void writeDriversAlloc(const parseTag_t *parse);
static void writeThreadsAlloc(const parseTag_t *parse);
static void writeRunlevelsAlloc(const parseTag_t *parse);
static void writeErrorCatalog(const parseTag_t *parse);
static void writeErrorEnum(const parseTag_t *parse);
static void writeModulesList(const parseTag_t *parse);
static void writeHalDefine(const parseTag_t *parse);
static void writeHalInit(const parseTag_t *parse);

#define HAVE_TAG(X)                                                  \
	X(HAVE_THREADS_ALLOC, "threads_alloc", writeThreadsAlloc)        \
	X(HAVE_DRIVERS_ALLOC, "drivers_alloc", writeDriversAlloc)        \
	X(HAVE_RUNLEVEL_ALLOC, "runlevels_alloc", writeRunlevelsAlloc)   \
	X(HAVE_RUNLEVEL_DEFINE, "runlevels_define", writeRunlevelDefine) \
	X(HAVE_ERROR_ENUM, "error_enum", writeErrorEnum)                 \
	X(HAVE_ERROR_CATALOG, "error_catalog", writeErrorCatalog)        \
	X(HAVE_INFO, "system_info", writeInfo)                           \
	X(HAVE_HAL_DEFINE, "hal_define", writeHalDefine)                 \
	X(HAVE_HAL_INIT, "hal_init", writeHalInit)                       \
	X(HAVE_MOD_COUNT, "modules_count", writeModulesCount)            \
	X(HAVE_MOD_LIST, "modules_list", writeModulesList)

static const struct
{
	const char *tag;
	void (*func)(const parseTag_t *parse);
} tags_cmds[] = {
#define X(e, s, f) {(s), (f)},
	HAVE_TAG(X)
#undef X
		{NULL, NULL}};

enum
{
#define X(e, s, f) e,
	HAVE_TAG(X)
#undef X
		HAVE_COUNT
} have_tag_id;

static const char *have_to_string[HAVE_COUNT] = {
#define X(e, s, f) [e] = (s),
	HAVE_TAG(X)
#undef X
};

static int have_tag_count[HAVE_COUNT];

static const char *string_from_have(const int id)
{
#define X(e, s, f) \
	if( id == (e) ) { return have_to_string[e]; }
	HAVE_TAG(X)
#undef X
	return NULL;
}

static int tagCmdDispatch(const char *cmd, const parseTag_t *parse)
{
	for( int i = 0; tags_cmds[i].tag != NULL; i++ )
	{
		if( strcmp(cmd, tags_cmds[i].tag) == 0 )
		{
			(*tags_cmds[i].func)(parse);
			return 0;
		}
	}
	return -1;
}

void parseTagInit(void)
{
	// initialise required options
	for( int i = 0; i < HAVE_COUNT; i++ ) { have_tag_count[i] = 0; }
}

void parseTag(modules_database_t *data_base, const char *file_name, const error_catalog_t *errors,
			  const options_list_t *auto_options)
{
	// open source and tmp file
	msgInfo("open <%s>", file_name);

	file_t file_src;
	fileInit(&file_src);
	file_src.name = (char *)file_name;
	fileOpen(&file_src, "r", FILE_READONLY, __FILE__, __LINE__);

	file_t file_tmp;
	fileInit(&file_tmp);
	fileMakeTmp(file_src.name, &file_tmp, __FILE__, __LINE__);

	parseTag_t parse = {.data_base = data_base,
						.file = file_tmp.stream,
						.errors = errors,
						.auto_options = auto_options};

	// read form source
	int tag_section = 0;
	int file_line_number = 0;
	tokenizer_t tok;

	while( fgets(tok.line, TOKEN_LINE_SIZE_MAX, file_src.stream) )
	{
		file_line_number++;
		tokenizer(&tok);

		if( !(strcmp(tok.tokens[0], "//")) && !(strcmp(tok.tokens[1], "[autoCode_tag]")) )
		{
			if( tok.count != 3 )
			{
				msgError("token count != 3 tok.line [%s:%i] %s",
						 file_src.name,
						 file_line_number,
						 tok.line);
				break;
			}

			if( tag_section == 1 )
			{
				msgError("Start new tag section without previous end tag [/tag] [%s:%i] %s",
						 file_src.name,
						 file_line_number,
						 tok.line);
				break;
			}

			msgInfo("found tag %s", tok.tokens[2]);

			fprintf(file_tmp.stream, "%s", tok.line);

			fprintf(file_tmp.stream, "// clang-format off\n");

			fprintf(file_tmp.stream, "/*\n");
			fprintf(file_tmp.stream, " * do not edit code between tag\n");
			fprintf(file_tmp.stream, " * code generated by autoCode, any change will be lost\n");
			fprintf(file_tmp.stream, " */\n\n");

			tag_section = 1;

			int err = tagCmdDispatch(tok.tokens[2], &parse);

			if( err != 0 )
			{
				msgError("unknown tag [%s:%i] %s\n", file_name, file_line_number, tok.tokens[2]);
				exit(1);
			}
		}

		if( !(strcmp(tok.tokens[0], "//")) && !(strcmp(tok.tokens[1], "[/tag]")) )
		{
			fprintf(file_tmp.stream, "// clang-format on\n");
			msgInfo("end tag");
			tag_section = 0;
		}

		if( tag_section == 0 ) { fprintf(file_tmp.stream, "%s", tok.line); }
	}

	if( tag_section == 1 )
	{
		msgError("missing end tag [/tag] [%s:%i]", file_src.name, file_line_number);
		exit(1);
	}

	fileCmpReplace(&file_src, &file_tmp);

	fileClose(&file_src, __FILE__, __LINE__);
	fileClose(&file_tmp, __FILE__, __LINE__);
}

void parseTagHave(void)
{
	// test required options
	for( int i = 0; i < HAVE_COUNT; i++ )
	{
		if( have_tag_count[i] == 0 )
		{
			msgError("required autoCode tag %s is not set", string_from_have(i));
			exit(1);
		}

		if( have_tag_count[i] > 1 )
		{
			msgError("required autoCode tag %s is multiple set", string_from_have(i));
			exit(1);
		}
	}
}

static void writeHalInit(const parseTag_t *parse)
{
	file_t file_list;
	fileInit(&file_list);
	file_list.name = (char *)parse->auto_options->file_halinit_list;
	fileOpen(&file_list, "r", FILE_READONLY, __FILE__, __LINE__);

	tokenizer_t tok;
	while( fgets(tok.line, TOKEN_LINE_SIZE_MAX, file_list.stream) )
	{
		tokenizer(&tok);
		fprintf(parse->file, "#include \"%s\"\n", tok.tokens[0]);
	}
	fileClose(&file_list, __FILE__, __LINE__);
	
	have_tag_count[HAVE_HAL_INIT]++;

}

static void writeHalDefine(const parseTag_t *parse)
{
	file_t file_list;
	fileInit(&file_list);
	file_list.name = (char *)parse->auto_options->file_haldefine_list;
	fileOpen(&file_list, "r", FILE_READONLY, __FILE__, __LINE__);

	tokenizer_t tok;
	while( fgets(tok.line, TOKEN_LINE_SIZE_MAX, file_list.stream) )
	{
		tokenizer(&tok);
		fprintf(parse->file, "#include \"%s\"\n", tok.tokens[0]);
	}
	fileClose(&file_list, __FILE__, __LINE__);

	have_tag_count[HAVE_HAL_DEFINE]++;
}

static void writeModulesList(const parseTag_t *parse)
{
	const module_type_t *mod = &parse->data_base->modules_type[TM_MOD_THREAD_ID];

	for( int i = 0; i < mod->modules_count; i++ )
	{
		if( mod->modules[i].subtype == TM_MOD_THREAD_TYPE_SYS )
		{
			fprintf(parse->file, "#include \"services/%s.h\"\n", mod->modules[i].name);
		}
		if( mod->modules[i].subtype == TM_MOD_THREAD_TYPE_USER )
		{
			fprintf(parse->file, "#include \"tasks/%s.h\"\n", mod->modules[i].name);
		}
	}
	fprintf(parse->file, "\n");

	mod = &parse->data_base->modules_type[TM_MOD_DRIVERS_ID];

	for( int i = 0; i < mod->modules_count; i++ )
	{
		fprintf(parse->file, "#include \"public/%s.h\"\n", mod->modules[i].name);
	}
	have_tag_count[HAVE_MOD_LIST]++;
}

static void writeRunlevelDefine(const parseTag_t *parse)
{
	for( int i = 0; i < RUN_LEVEL_COUNT; i++ )
	{
		fprintf(parse->file,
				"#define RUN_LEVEL%i_THREADS_COUNT %i\n",
				i,
				parse->data_base->threads_count[i]);
	}
	// structure
	fprintf(parse->file, "\ntypedef struct\n");
	fprintf(parse->file, "{\n");

	for( int i = 0; i < RUN_LEVEL_COUNT; i++ )
	{
		fprintf(parse->file, "\tuint8_t level%i[RUN_LEVEL%i_THREADS_COUNT + 1];\n", i, i);
	}

	fprintf(parse->file, "\tuint8_t *levels[%i];\n", RUN_LEVEL_COUNT);
	fprintf(parse->file, "\tuint8_t current;\n");
	fprintf(parse->file, "\tuint8_t next;\n");
	fprintf(parse->file, "} rl_data_base_t;\n\n");

	have_tag_count[HAVE_RUNLEVEL_DEFINE]++;
}

static void writeModulesCount(const parseTag_t *parse)
{
	fprintf(parse->file,
			"#define TM_MOD_DRIVER_COUNT %i\n",
			parse->data_base->modules_type[TM_MOD_DRIVERS_ID].modules_count);
	fprintf(parse->file,
			"#define TM_MOD_THREAD_COUNT %i\n",
			parse->data_base->modules_type[TM_MOD_THREAD_ID].modules_count);

	have_tag_count[HAVE_MOD_COUNT]++;
}

static void writeInfo(const parseTag_t *parse)
{
	fprintf(parse->file, "TM_STR_ROM_NEW(tm_ver, \"%s\");\n", parse->auto_options->tm_ver);
	fprintf(parse->file, "const uint16_t tm_build = %i;\n", atoi(parse->auto_options->tm_build));
	have_tag_count[HAVE_INFO]++;
}

static void writeThreadsAlloc(const parseTag_t *parse)
{
	int threads_count = 0;
	const module_type_t *mod;

	fprintf(parse->file, "\tmod_thread_item_t *mod;\n");

	mod = &parse->data_base->modules_type[TM_MOD_THREAD_ID];

	for( int i = 0; i < mod->modules_count; i++ )
	{

		fprintf(parse->file, "\n\tmod = mod_threadGetPointer(%i);\n", threads_count);

		fprintf(parse->file,
				"\n\thal_threadContextInit(%s, &(mod->stack_pointer), "
				"&(mod->stack[TM_MOD_THREAD_STACK_SIZE - 1]));\n",
				mod->modules[i].name);

		fprintf(parse->file, "\tmod->software_time_counter = 0;\n");
		fprintf(parse->file,
				"\tTM_STR_ROM_NEW(thread%i_name, \"%s\");\n",
				threads_count,
				mod->modules[i].name);
		fprintf(parse->file, "\tmod->name = &thread%i_name;\n", threads_count);
		fprintf(parse->file, "\tmod->status = %i;\n", mod->modules[i].status);
		fprintf(parse->file, "\tmod->main = %s;\n", mod->modules[i].name);

		threads_count++;
	}
	have_tag_count[HAVE_THREADS_ALLOC]++;
}

static void writeDriversAlloc(const parseTag_t *parse)
{
	const module_type_t *mod = &parse->data_base->modules_type[TM_MOD_DRIVERS_ID];

	fprintf(parse->file, "\tmod_driver_item_t *mod;\n");

	for( int i = 0; i < mod->modules_count; i++ )
	{
		fprintf(parse->file, "\n\tmod = mod_driverGetPointer(%i);\n", i);

		fprintf(parse->file, "\tTM_STR_ROM_NEW(driver%i_name, \"%s\");\n", i, mod->modules[i].name);
		fprintf(parse->file, "\t*(mod) = (mod_driver_item_t)\n");
		fprintf(parse->file, "\t{\n");
		fprintf(parse->file, "\t\t.name = &driver%i_name,\n", i);
		fprintf(parse->file, "\t\t.status = %i,\n", mod->modules[i].status);
		fprintf(parse->file, "\t\t.init = %sInit,\n", mod->modules[i].name);
		fprintf(parse->file, "\t\t.start = %sStart,\n", mod->modules[i].name);
		fprintf(parse->file, "\t\t.stop = %sStop\n", mod->modules[i].name);
		fprintf(parse->file, "\t};\n");
	}
	have_tag_count[HAVE_DRIVERS_ALLOC]++;
}

static void writeRunlevelsAlloc(const parseTag_t *parse)
{
	// data
	fprintf(parse->file, "\tto_run = (rl_data_base_t){\n");

	for( int level = 0; level < RUN_LEVEL_COUNT; level++ )
	{

		fprintf(parse->file, "\t\t.level%i = {%i", level, parse->data_base->threads_count[level]);

		// write threads list for run level
		int threads_count = 0;
		const module_type_t *mod;

		mod = &parse->data_base->modules_type[TM_MOD_THREAD_ID];

		for( int i = 0; i < mod->modules_count; i++ )
		{
			if( (mod->modules[i].status & RUN_LEVEL_MASK) <= level )
			{
				fprintf(parse->file, ",%i", threads_count++);
			}
		}
		fprintf(parse->file, "},\n");
	}

	fprintf(parse->file,
			"\t\t.levels = {to_run.level0, to_run.level1, to_run.level2, "
			"to_run.level3, to_run.level4}\n");
	fprintf(parse->file, "\t};\n");

	fprintf(parse->file, "\tto_run.current=RUN_CORE;\n");
	fprintf(parse->file, "\tto_run.next=RUN_CORE;\n");

	have_tag_count[HAVE_RUNLEVEL_ALLOC]++;
}

static void writeErrorCatalog(const parseTag_t *parse)
{

	for( int i = 0; i < parse->errors->error_count; i++ )
	{
		fprintf(parse->file, "TM_STR_ROM_NEW(err%i, %s);\n", i, parse->errors->catalog[i].message);
	}

	fprintf(parse->file, "\nconst err_item_t error_catalog[] = \n{\n");

	for( int i = 0; i < parse->errors->error_count; i++ )
	{
		fprintf(parse->file, "\t{&err%i, %i},\n", i, parse->errors->catalog[i].critical);
	}
	fprintf(parse->file, "};\n");

	have_tag_count[HAVE_ERROR_CATALOG]++;
}

static void writeErrorEnum(const parseTag_t *parse)
{
	// write errors enum
	fprintf(parse->file, "typedef enum\n");
	fprintf(parse->file, "{\n");

	for( int i = 0; i < parse->errors->error_count; i++ )
	{
		fprintf(parse->file, "\t%s,\n", parse->errors->catalog[i].name);
	}
	fprintf(parse->file, "\tERROR_COUNT\n");
	fprintf(parse->file, "} err_codes_t;\n\n");

	have_tag_count[HAVE_ERROR_ENUM]++;
}
