/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file error.c
 * @brief error implementation.
 *
 */

#include "error.h"

#include "tm_libc/tm_string.h"

// [autoCode_tag] error_catalog
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

TM_STR_ROM_NEW(err0, "HAL LCD cursor is out of range");
TM_STR_ROM_NEW(err1, "HAL RTC time value is out of range");
TM_STR_ROM_NEW(err2, "HAL I2C start condition failed");
TM_STR_ROM_NEW(err3, "HAL I2C address was not acknowledged");
TM_STR_ROM_NEW(err4, "HAL I2C write failed");
TM_STR_ROM_NEW(err5, "HAL I2C read failed");
TM_STR_ROM_NEW(err6, "HAL I2C scan complete");
TM_STR_ROM_NEW(err7, "hal USART TX buffer empty");
TM_STR_ROM_NEW(err8, "hal USART RX buffer empty");
TM_STR_ROM_NEW(err9, "hal USART TX buffer full");
TM_STR_ROM_NEW(err10, "hal USART RX buffer full");
TM_STR_ROM_NEW(err11, "No error");
TM_STR_ROM_NEW(err12, "Pointer is NULL");
TM_STR_ROM_NEW(err13, "I2C scan address buffer is full");
TM_STR_ROM_NEW(err14, "Most useless error in the world");
TM_STR_ROM_NEW(err15, "Second most useless error");
TM_STR_ROM_NEW(err16, "HAL driver control command is invalid");
TM_STR_ROM_NEW(err17, "HAL driver control value is invalid");
TM_STR_ROM_NEW(err18, "HAL driver state is inconsistent");
TM_STR_ROM_NEW(err19, "HAL driver is not initialized");
TM_STR_ROM_NEW(err20, "HAL driver is not running");
TM_STR_ROM_NEW(err21, "HAL driver is dead");
TM_STR_ROM_NEW(err22, "HAL driver dependency failed");

const err_item_t error_catalog[] = 
{
	{&err0, ERR_LEVEL_WARN},
	{&err1, ERR_LEVEL_WARN},
	{&err2, ERR_LEVEL_FAIL},
	{&err3, ERR_LEVEL_WARN},
	{&err4, ERR_LEVEL_FAIL},
	{&err5, ERR_LEVEL_FAIL},
	{&err6, ERR_LEVEL_FLOW},
	{&err7, ERR_LEVEL_FLOW},
	{&err8, ERR_LEVEL_FLOW},
	{&err9, ERR_LEVEL_FLOW},
	{&err10, ERR_LEVEL_WARN},
	{&err11, ERR_LEVEL_FLOW},
	{&err12, ERR_LEVEL_WARN},
	{&err13, ERR_LEVEL_WARN},
	{&err14, ERR_LEVEL_FAIL},
	{&err15, ERR_LEVEL_PANIC},
	{&err16, ERR_LEVEL_WARN},
	{&err17, ERR_LEVEL_WARN},
	{&err18, ERR_LEVEL_FAIL},
	{&err19, ERR_LEVEL_WARN},
	{&err20, ERR_LEVEL_WARN},
	{&err21, ERR_LEVEL_FAIL},
	{&err22, ERR_LEVEL_FAIL},
};

// clang-format on
// [/tag]

const tm_string_t *err_getMessage(uint8_t num)
{
	if( num < ERROR_COUNT ) { return error_catalog[num].name; }
	return 0;
}
