/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file error.c
 * @brief error implementation.
 *
 */

#include "error.h"

#include "tm_libc/tm_string.h"

// [autoCode_tag] error_catalog
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

TM_STR_ROM_NEW(err0, "HAL LCD cursor is out of range");
TM_STR_ROM_NEW(err1, "HAL RTC time value is out of range");
TM_STR_ROM_NEW(err2, "HAL I2C start condition failed");
TM_STR_ROM_NEW(err3, "HAL I2C address was not acknowledged");
TM_STR_ROM_NEW(err4, "HAL I2C write failed");
TM_STR_ROM_NEW(err5, "HAL I2C read failed");
TM_STR_ROM_NEW(err6, "hal USART TX buffer empty");
TM_STR_ROM_NEW(err7, "hal USART RX buffer empty");
TM_STR_ROM_NEW(err8, "hal USART TX buffer full");
TM_STR_ROM_NEW(err9, "hal USART RX buffer full");
TM_STR_ROM_NEW(err10, "No error");
TM_STR_ROM_NEW(err11, "Pointer is NULL");
TM_STR_ROM_NEW(err12, "Most useless error in the world");
TM_STR_ROM_NEW(err13, "Second most useless error");
TM_STR_ROM_NEW(err14, "HAL driver control command is invalid");
TM_STR_ROM_NEW(err15, "HAL driver control value is invalid");
TM_STR_ROM_NEW(err16, "HAL driver state is inconsistent");
TM_STR_ROM_NEW(err17, "HAL driver is not initialized");
TM_STR_ROM_NEW(err18, "HAL driver is not running");
TM_STR_ROM_NEW(err19, "HAL driver is dead");
TM_STR_ROM_NEW(err20, "HAL driver dependency failed");

const err_item_t error_catalog[] = 
{
	{&err0, 1},
	{&err1, 1},
	{&err2, 2},
	{&err3, 1},
	{&err4, 2},
	{&err5, 2},
	{&err6, 1},
	{&err7, 1},
	{&err8, 1},
	{&err9, 1},
	{&err10, 1},
	{&err11, 1},
	{&err12, 1},
	{&err13, 1},
	{&err14, 1},
	{&err15, 1},
	{&err16, 2},
	{&err17, 1},
	{&err18, 1},
	{&err19, 3},
	{&err20, 2},
};

// clang-format on
// [/tag]

const tm_string_t *err_getMessage(uint8_t num)
{
	if( num < ERROR_COUNT ) { return error_catalog[num].name; }
	return 0;
}
