/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file sc_threads.c
 * @brief Thread and system syscall implementation.
 */

/* =============================================================================
 * Declarations - Include
 * ===========================================================================*/

#include "sc_threads.h"

#include "hal/public/atomic.h"
#include "interfaces/tm_macros.h"
#include "interfaces/tm_modules.h"
#include "interfaces/tm_runLevel.h"
#include "system/sysCore/sys_modules.h"
#include "system/sysCore/sys_scheduler.h"
#include "system/sysCall/sc_string.h"

/* -----------------------------------------------
 * Thread name catalog
 * ---------------------------------------------*/

// [autoCode_tag] thread_name_catalog
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

TM_STR_NEW(thread0_name, "system");
TM_STR_NEW(thread1_name, "scli");
TM_STR_NEW(thread2_name, "task1");
TM_STR_NEW(thread3_name, "task2");

static const tm_string_t *const thread_name_catalog[MOD_THREAD_COUNT] =
{
	[0] = &thread0_name,
	[1] = &thread1_name,
	[2] = &thread2_name,
	[3] = &thread3_name,
};

// clang-format on
// [/tag]

/* -----------------------------------------------
 * Private function prototypes
 * ---------------------------------------------*/

static mod_thread_item_t *sc_threadGetPointer(const char *name);

/* =============================================================================
 * Implementation - Functions
 * ===========================================================================*/

/* -----------------------------------------------
 * Run level
 * ---------------------------------------------*/

uint8_t sc_runLevelGet(void)
{
	hal_atomic_state_t state = hal_atomicStart();
	uint8_t run_level = tm_schedulerRunLevelGet();
	hal_atomicEnd(state);
	return run_level;
}

bool sc_runLevelSet(uint8_t run_level)
{
	hal_atomic_state_t state = hal_atomicStart();
	bool result = tm_schedulerRunLevelSet(run_level);
	hal_atomicEnd(state);
	return result;
}

/* -----------------------------------------------
 * Software time counters
 * ---------------------------------------------*/

void sc_threadSetSTC(uint16_t count)
{
	hal_atomic_state_t state = hal_atomicStart();
	mod_threadSetSTC(count);
	hal_atomicEnd(state);
}

uint16_t sc_threadGetSTC(void)
{
	hal_atomic_state_t state = hal_atomicStart();
	uint16_t timer = mod_threadGetSTC();
	hal_atomicEnd(state);
	return timer;
}

/* -----------------------------------------------
 * Thread metadata
 * ---------------------------------------------*/

uint16_t sc_threadGetCount(void) { return MOD_THREAD_COUNT; }

bool sc_threadGetInfo(uint16_t id, const tm_string_t **name, uint8_t *run_level)
{
	if( (id >= MOD_THREAD_COUNT) || (name == 0) || (run_level == 0) ) { return false; }

	hal_atomic_state_t state = hal_atomicStart();
	mod_thread_item_t *thread = mod_threadGetPointer((uint8_t)id);
	*name = thread_name_catalog[id];
	*run_level = RL_GET_RUN_LEVEL(thread->status);
	hal_atomicEnd(state);

	return *name != 0;
}

/* -----------------------------------------------
 * Thread life cycle
 * ---------------------------------------------*/

void sc_threadSetInitialized(void)
{
	hal_atomic_state_t state = hal_atomicStart();
	mod_thread_item_t *thread = mod_threadGetPointer(mod_threadGetCurrent());
	TM_SETBIT(thread->status, THREAD_BIT_INITIALIZED);
	hal_atomicEnd(state);
}

bool sc_threadStart(const char *name, uint8_t initial_run_level)
{
	mod_thread_item_t *thread = sc_threadGetPointer(name);
	if( thread == 0 ) { return false; }

	hal_atomic_state_t state = hal_atomicStart();

	if( thread->saved_run_level == RL_RUN_NONE ) { thread->saved_run_level = initial_run_level; }
	else
	{
		thread->status &= (uint8_t)~RL_LEVEL_MASK;
		thread->status |= thread->saved_run_level;
	}

	hal_atomicEnd(state);
	return true;
}

bool sc_threadStop(const char *name)
{
	mod_thread_item_t *thread = sc_threadGetPointer(name);
	if( thread == 0 ) { return false; }

	hal_atomic_state_t state = hal_atomicStart();
	uint8_t current_run_level = RL_GET_RUN_LEVEL(thread->status);

	thread->saved_run_level = current_run_level;
	thread->status &= (uint8_t)~RL_LEVEL_MASK;

	hal_atomicEnd(state);
	return true;
}

bool sc_threadRunLevelIsReady(uint8_t run_level)
{
	if( (run_level == RL_RUN_NONE) || (run_level >= RL_LEVEL_COUNT) ) { return false; }

	bool ready = true;
	hal_atomic_state_t state = hal_atomicStart();
	for( uint8_t i = 0; i < MOD_THREAD_COUNT; i++ )
	{
		mod_thread_item_t *thread = mod_threadGetPointer(i);
		if( (RL_GET_RUN_LEVEL(thread->status) == run_level) &&
			((TM_GETBIT(thread->status, THREAD_BIT_INITIALIZED) == 0) ||
			 (TM_GETBIT(thread->status, THREAD_BIT_DEAD) != 0)) )
		{
			ready = false;
			break;
		}
	}
	hal_atomicEnd(state);

	return ready;
}

/* -----------------------------------------------
 * Cooperative scheduling
 * ---------------------------------------------*/

void sc_coopYield(void)
{
	hal_atomic_state_t state = hal_atomicStart();
	mod_thread_item_t *thread = mod_threadGetPointer(mod_threadGetCurrent());
	TM_SETBIT(thread->status, THREAD_BIT_YIELDED);
	tm_schedulerCoop();
	hal_atomicEnd(state);
	while( TM_GETBIT(thread->status, THREAD_BIT_YIELDED) );
}

/* -----------------------------------------------
 * Private helpers
 * ---------------------------------------------*/

static mod_thread_item_t *sc_threadGetPointer(const char *name)
{
	if( name == 0 ) { return 0; }

	for( uint8_t i = 0; i < MOD_THREAD_COUNT; i++ )
	{
		mod_thread_item_t *thread = mod_threadGetPointer(i);
		if( sc_stringCompare(*thread_name_catalog[i],
						 sc_stringFromBuffer(name),
						 MOD_NAME_SIZE_MAX) == 0 )
		{
			return thread;
		}
	}

	return 0;
}
