#
# TaskMate Project
# (c) 2025 PRADERE Sebastien
#
# This file is part of TaskMate and is distributed under the TaskMate License v1.0.
# See the LICENSE file for full license terms.
#
# Non-commercial use permitted under conditions. Commercial use requires a separate license.
# Commercial licensing inquiries: https://codeberg.org/Doul09/TaskMate/issues
#
# Powered by TaskMate, (c) 2025 PRADERE Sebastien
#

 
# Compiler 
CC = avr-gcc

# MCU and Programmer settings
MCU = atmega2560
F_CPU = 16000000UL
PROGRAMMER = avrispmkII
PORT = /dev/ttyU0

# Files
TARGET = TaskMate

#old SRC = sysCore/$(TARGET).c sysCore/sysCall.c sysCore/taskCreate.c drivers/timer1.c drivers/timer3.c tasks/task1.c tasks/task2.c
# Source directories
SRC_DIRS = drivers tasks sysCore
# Automatically gather all C files
SRCS != find $(SRC_DIRS) -name "*.c"

OBJ = $(SRCS:.c=.o) 
HEX = $(TARGET).hex
ELF = $(TARGET).elf

# Compiler flags
CFLAGS = -mmcu=$(MCU) -DF_CPU=$(F_CPU) -O2 -Wall -I/root/code/TaskMate/TaskMate_current -MMD -MP


# Build rules

all:$(OBJ)
	@echo
	@echo Start compilation ...
	@echo Sources SRC = $(SRCS)
	@echo Sources OBJ = $(OBJ)
	@echo
	
	#implicit build in rule *.c -> *.o
-include ${OBJS:.o=.d}
	#link objects
	$(CC) $(CFLAGS) -o $(ELF) $(OBJ)
	@echo
	@echo End of compilation
	
upload:all
	#to hex format
	avr-objcopy -O ihex -R .eeprom $(ELF) $(HEX)
	#upload to atmega
	avrdude -c $(PROGRAMMER) -p $(MCU) -U flash:w:$(HEX):i -P $(PORT) -D
	
clean:
	rm -f  $(ELF) $(HEX) $(OBJ) *.out *.d $(SRCS:.c=.d)
	
dump:all
	avr-objcopy -O ihex -R .eeprom $(ELF) $(HEX)
	avr-objdump -D -m avr6 $(HEX) > hex.out
	avr-objdump -D -m avr6 $(ELF) > elf.out
	
doc:
	doxygen Doxyfile
