################################################################################
#
# TaskMate Project
# (c) 2026 PRADERE Sebastien
#
# This file is part of TaskMate and is distributed under the BSD-2-Clause License.
# See the LICENSE file for full license terms.
#
################################################################################

################################################################################
# allow {ed source access system critical headers
################################################################################

{
pattern hal/public/hal_context.h
allow {
	sysCore/modules.c 
	sysCore/tm_scheduler.c
	}
}

{
pattern hal/public/hal_stack.h
allow { 
	sysCore/tm_scheduler.c
	}
}

{
pattern hal/public/hal_int.h
allow { 
	hal/public/panic.h 
	sysCore/tm_scheduler.c
	}
}

{
pattern sysCore/runLevel.h
allow { 
	sysCore/runLevel.c 
	autoCode/autoCode.c 
	autoCode/autoCode.h 
	sysCore/boot.c
	}
}

{
pattern interfaces/modules_define.h
allow { 
	sysCore/modules.h 
	autoCode/autoCode.c 
	autoCode/autoCode.h 
	hal/arch/avr8/hal_context_impl.c
	}
}

{
pattern interfaces/runLevel_define.h
allow { 
	sysCore/runLevel.h 
	sysCore/boot.c
	}
}

{
pattern sysCore/modules_list.h
allow { 
	autoCode/autoCode.c 
	sysCore/modules.c
	}
}

{
pattern sysCore/hal_init.h
allow { 
	autoCode/autoCode.c 
	sysCore/boot.c 
	sysCore/gpio.c
	}
}
