/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file hal_sysInfo.c
 * @brief public hal_sysInfo implementation.
 *
 */

#include "hal/public/hal_sysInfo.h"

#include "hal/public/hal_tmlibc.h"

// [autoCode_tag] system info
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

TM_STR_ROM_NEW(tm_ver, "0.27");
const uint16_t tm_build = 4830;
TM_STR_ROM_NEW(arch_name, "avr8");
TM_STR_ROM_NEW(mcu_name, "atmega2560");
TM_STR_ROM_NEW(board_name, "arduinoMega");

// clang-format on
// [/tag]

static const hal_info_t info = {.tm_ver = &tm_ver,
								.tm_build = tm_build,
								.arch = &arch_name,
								.mcu = &mcu_name,
								.board = &board_name};

void hal_sysInfoGet(const hal_info_t **dest) { *dest = &info; }
