/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file hal_define.h
 * @brief hal define
 */

#ifndef HAL_DEFINE_H
#define HAL_DEFINE_H

// [autoCode_tag] hal define
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

#include "hal/arch/avr8/arch_define.h"
#include "hal/mcu/atmega2560/mcu_define.h"
#include "hal/board/arduinoMega/board_define.h"

// clang-format on
// [/tag]

#endif
