/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the TaskMate License
 * v1.0. See the LICENSE file for full license terms.
 *
 * Non-commercial use permitted under conditions. Commercial use requires a
 * separate license. Commercial licensing inquiries:
 * https://codeberg.org/Doul09/TaskMate/issues
 *
 * Powered by TaskMate, (c) 2026 PRADERE Sebastien
 */

/**
 * @file hal_sysInfo.c
 * @brief System informations
 *
 */

#include "hal/public/hal_sysInfo.h"

 // [autoCode_tag] system info
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

TM_STR_ROM_NEW(tm_ver, "0.26");
const uint16_t tm_build = 4606;
TM_STR_ROM_NEW(arch_name, "avr8");
TM_STR_ROM_NEW(mcu_name, "atmega2560");
TM_STR_ROM_NEW(board_name, "arduinoMega");

// clang-format on
// [/tag]

static const hal_info_t info = {.tm_ver = &tm_ver,
							   .tm_build = tm_build,
							   .arch = &arch_name,
							   .mcu = &mcu_name,
							   .board = &board_name};

void hal_sysInfoGet(const hal_info_t **dest) { *dest = &info; }
