################################################################################
#
# TaskMate Project
# (c) 2026 PRADERE Sebastien
#
# This file is part of TaskMate and is distributed under the BSD-2-Clause License.
# See the LICENSE file for full license terms.
#
################################################################################

################################################################################
# allowed source access system critical headers
################################################################################

{
pattern hal/public/context.h
allow {
	system/sysCore/modules.c 
	system/sysCore/tm_scheduler.c
	}
}

{
pattern hal/public/stack.h
allow { 
	system/sysCore/tm_scheduler.c
	}
}

{
pattern hal/public/interrupt.h
allow { 
	hal/public/panic.h 
	system/sysCore/tm_scheduler.c
	}
}

{
pattern interfaces/modules_define.h
allow { 
	system/sysCore/modules.h 
	system/sysCore/modules.c
	system/sysCore/boot.c
	system/sysCore/tm_scheduler.c
	system/services/commands/driver.c
	autoCode/autoCode.c 
	autoCode/autoCode.h 
	hal/arch/avr8/context.c
	hal/drivers/lcd_AMC2004/lcd_AMC2004.c
	hal/drivers/rtc_ZS042/rtc_ZS042.c
	hal/mcu/atmega2560/i2c.c
	hal/mcu/atmega2560/timerSched.c
	hal/mcu/atmega2560/timerSTC.c
	hal/mcu/atmega2560/usart.c
	system/sysCall/sysCall.c
	}
}

{
pattern interfaces/runLevel_define.h
allow { 
	system/sysCore/runLevel.h 
	system/sysCore/boot.c
	system/sysCore/tm_scheduler.c
	system/sysCall/sysCall.c
	autoCode/autoCode.h
	hal/drivers/lcd_AMC2004/lcd_AMC2004.c
	hal/drivers/rtc_ZS042/rtc_ZS042.c
	hal/mcu/atmega2560/i2c.c
	hal/mcu/atmega2560/timerSched.c
	hal/mcu/atmega2560/timerSTC.c
	hal/mcu/atmega2560/usart.c
	}
}

{
pattern system/sysCore/modules_list.h
allow { 
	autoCode/autoCode.c 
	system/sysCore/modules.c
	system/sysCore/boot.c
	system/sysCore/tm_scheduler.c
	}
}

{
pattern system/sysCore/hal_init.h
allow { 
	autoCode/autoCode.c 
	system/sysCore/boot.c 
	system/sysCore/gpio.c
	}
}
