################################################################################
#
# TaskMate Project
# (c) 2026 PRADERE Sebastien
#
# This file is part of TaskMate and is distributed under the BSD-2-Clause License.
# See the LICENSE file for full license terms.
#
################################################################################

################################################################################
# allowed source access system critical headers
################################################################################

{
pattern hal/public/context.h
allow {
	system/sysCore/modules.c 
	system/sysCore/tm_scheduler.c
	}
}

{
pattern hal/public/stack.h
allow { 
	system/sysCore/tm_scheduler.c
	}
}

{
pattern hal/public/interrupt.h
allow { 
	hal/public/panic.h 
	system/sysCore/tm_scheduler.c
	}
}

{
pattern system/sysCore/modules_list.h
allow { 
	autoCode/autoCode.c 
	system/sysCore/modules.c
	system/sysCore/boot.c
	system/sysCore/tm_scheduler.c
	}
}

{
pattern system/sysCore/hal_init.h
allow { 
	autoCode/autoCode.c 
	system/sysCore/boot.c 
	system/sysCore/gpio.c
	}
}
