# Programs used by the portable build and project utilities
awk
bmake
cat
clang
clang-format19
clang-tidy19
cloc
cppcheck
ctags
cut
date
doxygen
find
git
grep
head
ls
mkdir
mount
printf
rm
rsync
sed
sort
touch
umount
xargs
