# ###############################################################################
#
# TaskMate Project
# (c) 2026 PRADERE Sebastien
#
# This file is part of TaskMate and is distributed under the BSD-2-Clause License.
# See the LICENSE file for full license terms.
#
# ###############################################################################

# ###############################################################################
# allowed source access system critical headers
# ###############################################################################

{
source_file hal/public/context.h
allow {
	system/sysCore/sys_modules.c
	system/sysCore/sys_scheduler.c
	}
}

{
source_file hal/public/stack.h
allow { 
	system/sysCore/sys_scheduler.c
	}
}

{
source_file hal/public/interrupt.h
allow { 
	system/sysCore/sys_scheduler.c
	}
}

{
source_file system/sysCore/sys_modules_list.h
allow { 
	autoCode/autoCode.c 
	system/sysCore/sys_modules.c
	system/sysCore/sys_scheduler.c
	}
}

{
source_file system/sysCore/sys_hal_init.h
allow { 
	autoCode/autoCode.c 
	system/TaskMate.c 
	system/sysCore/sys_gpio.c
	}
}
