/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file modules_define.h
 * @brief interfaces modules_define header declarations.
 */

#ifndef MODULES_DEFINE_H
#define MODULES_DEFINE_H

#if !defined(TM_SYSTEM_CRITICAL_ALLOWED)
	#error "NOT ALLOWED INCLUDE : modules_define.h"
#endif

// [autoCode_tag] modules_count
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

#define TM_MOD_DRIVER_COUNT 6
#define TM_MOD_THREAD_COUNT 4
// clang-format on
// [/tag]

// definitions for autoCode
#define TM_MOD_COUNT_MAX 256

#define TM_MOD_DRIVERS_ID 0
#define TM_MOD_THREAD_ID 1
#define TM_MOD_THREAD_SYS_ID 2
#define TM_MOD_THREAD_USER_ID 3

#define TM_MOD_TYPE_COUNT 2
#define TM_MOD_NAME_SIZE_MAX 32

// system
#define TM_MOD_THREAD_STACK_SIZE 256

// thread status bits
// bit [2 1 0 ] is run level
#define TM_MOD_THREAD_TYPE_USER 3
#define TM_MOD_THREAD_TYPE_SYS 4
#define TM_MOD_THREAD_DEAD 5

// driver status bits
// bit [2 1 0 ] is run level
#define TM_MOD_DRIVER_LOCK 3
#define TM_MOD_DRIVER_DEAD 4
#define TM_MOD_DRIVER_INIT 5

#endif
