/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file define.h
 * @brief hal define
 */

#ifndef HAL_DEFINE_H
#define HAL_DEFINE_H

// [autoCode_tag] hal_define
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

#include "srcs/hal/board/arduinoMega/board_define.h"
#include "srcs/hal/mcu/atmega2560/mcu_define.h"
#include "srcs/hal/arch/avr8/arch_define.h"
// clang-format on
// [/tag]

#endif
