/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file hal_define.h
 * @brief define header declarations.
 */

#ifndef HAL_PUBLIC_HAL_DEFINE_H
#define HAL_PUBLIC_HAL_DEFINE_H

/* ============================================================================
 * Generated includes
 * ========================================================================== */

// [autoCode_tag] hal_define
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

#include "srcs/user/target/test1/define.h"
#include "srcs/hal/board/arduinoMega/mega_define.h"
#include "srcs/hal/mcu/atmega2560/at2560_define.h"
#include "srcs/hal/arch/avr8/avr8_define.h"

// clang-format on
// [/tag]

#endif // HAL_PUBLIC_HAL_DEFINE_H
