/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file sysInfo.c
 * @brief sys info implementation.
 *
 */

#include "hal/public/sysInfo.h"

#include "hal/public/tmlibc.h"

// [autoCode_tag] system_info
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

TM_STR_ROM_NEW(tm_ver, "0.28");
const uint16_t tm_build = 523;

// clang-format on
// [/tag]

static const hal_info_t info = {.tm_ver = &tm_ver, .tm_build = tm_build};

void hal_sysInfoGet(const hal_info_t **dest) { *dest = &info; }
