/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file hal_init.h
 * @brief hal init
 */

#ifndef SYSCORE_HAL_INIT_H
#define SYSCORE_HAL_INIT_H

#if !defined(HAL_SYSTEM_CRITICAL_ALLOWED)
	#error "NOT ALLOWED INCLUDE : hal_init.h"
#endif

// [autoCode_tag] hal_init
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

#include "srcs/user/target/test1/targetInit.h"
#include "srcs/hal/board/arduinoMega/boardInit.h"
#include "srcs/hal/mcu/atmega2560/mcuInit.h"
#include "srcs/hal/arch/avr8/archInit.h"

// clang-format on
// [/tag]

#endif // SYSCORE_HAL_INIT_H
