/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file modules_list.h
 * @brief modules list header declarations.
 */

#ifndef SYSCORE_MODULES_LIST_H
#define SYSCORE_MODULES_LIST_H

#if !defined(TM_SYSTEM_CRITICAL_ALLOWED)
	#error "NOT ALLOWED INCLUDE : modules_list.h"
#endif

/* ============================================================================
 * Generated includes
 * ========================================================================== */

// [autoCode_tag] modules_list
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

#include "system/services/system.h"
#include "system/services/scli.h"
#include "user/tasks/task1.h"
#include "user/tasks/task2.h"

#include "interfaces/drv_timerSched.h"
#include "interfaces/drv_timerSTC.h"
#include "interfaces/drv_usart.h"
#include "interfaces/drv_i2c.h"
#include "interfaces/drv_lcd.h"
#include "interfaces/drv_rtc.h"

// clang-format on
// [/tag]

#endif // SYSCORE_MODULES_LIST_H
