/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file runLevel.h
 * @brief sysCore runLevel header declarations.
 *
 */

#ifndef SYSCORE_RUNLEVEL_H
#define SYSCORE_RUNLEVEL_H

#include <stdint.h>

#if !defined(TM_SYSTEM_CRITICAL_ALLOWED)
	#error "NOT ALLOWED INCLUDE : runLevel.h"
#endif

#include "interfaces/runLevel_define.h"

// [autoCode_tag] runlevels_define
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

#define RUN_LEVEL0_THREADS_COUNT 0
#define RUN_LEVEL1_THREADS_COUNT 0
#define RUN_LEVEL2_THREADS_COUNT 0
#define RUN_LEVEL3_THREADS_COUNT 0
#define RUN_LEVEL4_THREADS_COUNT 0

typedef struct
{
	uint8_t level0[RUN_LEVEL0_THREADS_COUNT + 1];
	uint8_t level1[RUN_LEVEL1_THREADS_COUNT + 1];
	uint8_t level2[RUN_LEVEL2_THREADS_COUNT + 1];
	uint8_t level3[RUN_LEVEL3_THREADS_COUNT + 1];
	uint8_t level4[RUN_LEVEL4_THREADS_COUNT + 1];
	uint8_t *levels[5];
	uint8_t current;
	uint8_t next;
} rl_data_base_t;

// clang-format on
// [/tag]

void rl_Alloc(void);

#endif // SYSCORE_RUNLEVEL_H
