/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file runLevel.c
 * @brief run level implementation.
 *
 */

#include "system/sysCore/runLevel.h"

static rl_data_base_t to_run;

// NOLINTBEGIN
// NOLINT(readability-magic-numbers)

void rl_Alloc(void)
{

	// [autoCode_tag] runlevels_alloc
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

	to_run = (rl_data_base_t){
		.level0 = {0},
		.level1 = {0},
		.level2 = {0},
		.level3 = {0,0,1},
		.level4 = {0,0,1,2,3},
		.levels = {to_run.level0, to_run.level1, to_run.level2, to_run.level3, to_run.level4}
	};
	to_run.current=RUN_CORE;
	to_run.next=RUN_CORE;

// clang-format on
	// [/tag]
}

// NOLINTEND
