/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file sys_modules.c
 * @brief modules implementation.
 */

/* =============================================================================
 * Declarations - Include
 * ===========================================================================*/

#include "sys_modules.h"

#include "hal/public/context.h"
#include "interfaces/tm_modules.h"
#include "system/sysCore/sys_modules_list.h"

/* -----------------------------------------------
 * Private variables
 * ---------------------------------------------*/

static struct
{
	mod_driver_item_t drivers[MOD_DRIVER_COUNT];
	mod_thread_item_t threads[MOD_THREAD_COUNT];
	uint8_t thread_current;
} mod_data_base;

/* =============================================================================
 * Implementation - Functions
 * ===========================================================================*/

/* -----------------------------------------------
 * Module database access
 * ---------------------------------------------*/

void mod_threadSetCurrent(uint8_t n) { mod_data_base.thread_current = n; }
uint8_t mod_threadGetCurrent(void) { return mod_data_base.thread_current; }

void mod_threadSetSTC(uint16_t count)
{
	mod_data_base.threads[mod_data_base.thread_current].software_time_counter = count;
}

uint16_t mod_threadGetSTC(void)
{
	return mod_data_base.threads[mod_data_base.thread_current].software_time_counter;
}

mod_driver_item_t *mod_driverGetPointer(uint8_t id) { return &mod_data_base.drivers[id]; }
mod_thread_item_t *mod_threadGetPointer(uint8_t id) { return &mod_data_base.threads[id]; }

/* -----------------------------------------------
 * Static module allocation
 * ---------------------------------------------*/

// NOLINTBEGIN
// NOLINT(readability-magic-numbers)

void mod_threadsAlloc(void)
{
	for( uint8_t i = 0; i < MOD_THREAD_COUNT; i++ )
	{
		mod_thread_item_t *thread = mod_threadGetPointer(i);
		thread->canary_low = MOD_CANARY;
		thread->canary_high = MOD_CANARY;
	}

	// [autoCode_tag] threads_alloc
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

	mod_thread_item_t *mod;

	mod = mod_threadGetPointer(0);

	hal_threadContextInit(system, &(mod->stack_pointer), &(mod->stack[MOD_THREAD_STACK_SIZE - 1]));
	mod->software_time_counter = 0;
	mod->status = 17;
	mod->saved_run_level = 1;
	mod->main = system;

	mod = mod_threadGetPointer(1);

	hal_threadContextInit(scli, &(mod->stack_pointer), &(mod->stack[MOD_THREAD_STACK_SIZE - 1]));
	mod->software_time_counter = 0;
	mod->status = 19;
	mod->saved_run_level = 3;
	mod->main = scli;

	mod = mod_threadGetPointer(2);

	hal_threadContextInit(task1, &(mod->stack_pointer), &(mod->stack[MOD_THREAD_STACK_SIZE - 1]));
	mod->software_time_counter = 0;
	mod->status = 12;
	mod->saved_run_level = 4;
	mod->main = task1;

	mod = mod_threadGetPointer(3);

	hal_threadContextInit(task2, &(mod->stack_pointer), &(mod->stack[MOD_THREAD_STACK_SIZE - 1]));
	mod->software_time_counter = 0;
	mod->status = 12;
	mod->saved_run_level = 4;
	mod->main = task2;

// clang-format on
	// [/tag]
}

void mod_driversAlloc(void)
{
	// [autoCode_tag] drivers_alloc
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

	mod_driver_item_t *mod;
	hal_driver_control_data_t control_data;

	mod = mod_driverGetPointer(0);
	control_data.run_level = 0;
	hal_timerSchedControl(DRV_CTRL_RLSET, &control_data);
	*(mod) = (mod_driver_item_t)
	{
		.address = MOD_DRIVER_ADDRESS_NONE,
		.control = hal_timerSchedControl
	};

	mod = mod_driverGetPointer(1);
	control_data.run_level = 1;
	hal_timerSTCControl(DRV_CTRL_RLSET, &control_data);
	*(mod) = (mod_driver_item_t)
	{
		.address = MOD_DRIVER_ADDRESS_NONE,
		.control = hal_timerSTCControl
	};

	mod = mod_driverGetPointer(2);
	control_data.run_level = 0;
	hal_usartControl(DRV_CTRL_RLSET, &control_data);
	*(mod) = (mod_driver_item_t)
	{
		.address = MOD_DRIVER_ADDRESS_NONE,
		.control = hal_usartControl
	};

	mod = mod_driverGetPointer(3);
	control_data.run_level = 1;
	hal_i2cControl(DRV_CTRL_RLSET, &control_data);
	*(mod) = (mod_driver_item_t)
	{
		.address = MOD_DRIVER_ADDRESS_NONE,
		.control = hal_i2cControl
	};

	mod = mod_driverGetPointer(4);
	control_data.run_level = 2;
	hal_lcdControl(DRV_CTRL_RLSET, &control_data);
	*(mod) = (mod_driver_item_t)
	{
		.address = 0x3C,
		.control = hal_lcdControl
	};

	mod = mod_driverGetPointer(5);
	control_data.run_level = 2;
	hal_rtcControl(DRV_CTRL_RLSET, &control_data);
	*(mod) = (mod_driver_item_t)
	{
		.address = 0x68,
		.control = hal_rtcControl
	};

// clang-format on
	// [/tag]
}

// NOLINTEND
