#include "drivers/timer1.h"
#include "drivers/timer3.h"
#include "drivers/i2c.h"
#include "drivers/usart1.h"
#include "tasks/task1.h"
#include "tasks/task2.h"
#include "services/lcd.h"
#include "services/scli.h"
