/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file hal_init.h
 * @brief hal init
 */

#ifndef HAL_INIT_H
#define HAL_INIT_H

#if !defined(HAL_SYSTEM_CRITICAL_ALLOWED)
	#error "NOT ALLOWED INCLUDE : hal_init.h"
#endif

// [autoCode_tag] hal init
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

#include "hal/arch/avr8/hal_archInit.h"
#include "hal/mcu/atmega2560/hal_mcuInit.h"
#include "hal/board/arduinoMega/hal_boardInit.h"

// clang-format on
// [/tag]

#endif
