/*
 * TaskMate Project
 * (c) 2025 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the TaskMate License
 * v1.0. See the LICENSE file for full license terms.
 *
 * Non-commercial use permitted under conditions. Commercial use requires a
 * separate license. Commercial licensing inquiries:
 * https://codeberg.org/Doul09/TaskMate/issues
 *
 * Powered by TaskMate, (c) 2025 PRADERE Sebastien
 */

/**
 * @file modules.c
 * @brief module data base
 */

#include "sysCore/modules.h"

#include "hal/auto_hal_system.h"
#include "hal/auto_hal_user.h"
#include "sysCore/auto_threads_list.h"

static struct
{
	module_item_driver_t drivers[MODULES_DRIVER_COUNT];
	module_item_thread_t threads[MODULES_THREAD_COUNT];
	uint8_t thread_current;
} modules;

void moduleThreadSetCurrent(uint8_t n) { modules.thread_current = n; }
uint8_t moduleThreadGetCurrent(void) { return modules.thread_current; }

void moduleThreadSetSTC(uint16_t count)
{
	modules.threads[modules.thread_current].software_time_counter = count;
}

uint16_t moduleThreadGetSTC(void)
{
	return modules.threads[modules.thread_current].software_time_counter;
}

module_item_driver_t *moduleDriverGetPointer(uint8_t id) { return &modules.drivers[id]; }
module_item_thread_t *moduleThreadGetPointer(uint8_t id) { return &modules.threads[id]; }

// NOLINTBEGIN
// NOLINT(readability-magic-numbers)

void modulesThreadsAlloc(void)
{
	// [autoCode_tag] threads alloc
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

	module_item_thread_t *mod;

	mod = moduleThreadGetPointer(0);

	hal_threadContextInit(scli, &(mod->stack_pointer), &(mod->stack[THREAD_STACK_SIZE - 1 ]));
	mod->software_time_counter = 0;
	const char *thread0_name = "scli";
	mod->name = thread0_name;
	mod->status = 19;
	mod->main = scli;

	mod = moduleThreadGetPointer(1);

	hal_threadContextInit(msg, &(mod->stack_pointer), &(mod->stack[THREAD_STACK_SIZE - 1 ]));
	mod->software_time_counter = 0;
	const char *thread1_name = "msg";
	mod->name = thread1_name;
	mod->status = 19;
	mod->main = msg;

	mod = moduleThreadGetPointer(2);

	hal_threadContextInit(task1, &(mod->stack_pointer), &(mod->stack[THREAD_STACK_SIZE - 1 ]));
	mod->software_time_counter = 0;
	const char *thread2_name = "task1";
	mod->name = thread2_name;
	mod->status = 12;
	mod->main = task1;

	mod = moduleThreadGetPointer(3);

	hal_threadContextInit(task2, &(mod->stack_pointer), &(mod->stack[THREAD_STACK_SIZE - 1 ]));
	mod->software_time_counter = 0;
	const char *thread3_name = "task2";
	mod->name = thread3_name;
	mod->status = 12;
	mod->main = task2;
	// [/tag]
}

void modulesDriversAlloc(void)
{
	// [autoCode_tag] drivers alloc
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

	module_item_driver_t *mod;

	mod = moduleDriverGetPointer(0);
	const char *driver0_name = "hal_timerScheduler";
	*(mod) = (module_item_driver_t)
	{
		.name = driver0_name,
		.status = 1,
		.init = hal_timerSchedulerInit,
		.start = hal_timerSchedulerStart,
		.stop = hal_timerSchedulerStop
	};

	mod = moduleDriverGetPointer(1);
	const char *driver1_name = "hal_timerSTC";
	*(mod) = (module_item_driver_t)
	{
		.name = driver1_name,
		.status = 1,
		.init = hal_timerSTCInit,
		.start = hal_timerSTCStart,
		.stop = hal_timerSTCStop
	};

	mod = moduleDriverGetPointer(2);
	const char *driver2_name = "hal_i2c";
	*(mod) = (module_item_driver_t)
	{
		.name = driver2_name,
		.status = 1,
		.init = hal_i2cInit,
		.start = hal_i2cStart,
		.stop = hal_i2cStop
	};

	mod = moduleDriverGetPointer(3);
	const char *driver3_name = "hal_usart";
	*(mod) = (module_item_driver_t)
	{
		.name = driver3_name,
		.status = 1,
		.init = hal_usartInit,
		.start = hal_usartStart,
		.stop = hal_usartStop
	};

	mod = moduleDriverGetPointer(4);
	const char *driver4_name = "hal_lcd";
	*(mod) = (module_item_driver_t)
	{
		.name = driver4_name,
		.status = 2,
		.init = hal_lcdInit,
		.start = hal_lcdStart,
		.stop = hal_lcdStop
	};

	mod = moduleDriverGetPointer(5);
	const char *driver5_name = "hal_ZS_042";
	*(mod) = (module_item_driver_t)
	{
		.name = driver5_name,
		.status = 2,
		.init = hal_ZS_042Init,
		.start = hal_ZS_042Start,
		.stop = hal_ZS_042Stop
	};
	// [/tag]
}

// NOLINTEND
