/*
 * TaskMate Project
 * (c) 2025 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the TaskMate License
 * v1.0. See the LICENSE file for full license terms.
 *
 * Non-commercial use permitted under conditions. Commercial use requires a
 * separate license. Commercial licensing inquiries:
 * https://codeberg.org/Doul09/TaskMate/issues
 *
 * Powered by TaskMate, (c) 2025 PRADERE Sebastien
 */

/**
 * @file modules.h
 * @brief module data base header
 */

#ifndef MODULES_H
#define MODULES_H

#include "sysCore/modules_items.h"

// [autoCode_tag] modules count
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

#define MODULES_DRIVER_COUNT 6
#define MODULES_THREAD_COUNT 4
// [/tag]

void moduleThreadSetCurrent(uint8_t n);
uint8_t moduleThreadGetCurrent(void);

void moduleThreadSetRTC(uint16_t count);
uint16_t moduleThreadGetRTC(void);

module_item_driver_t *moduleDriverGetPointer(uint8_t id);
module_item_thread_t *moduleThreadGetPointer(uint8_t id);

void modulesThreadsAlloc(void);
void modulesDriversAlloc(void);

#endif
