/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the TaskMate License
 * v1.0. See the LICENSE file for full license terms.
 *
 * Non-commercial use permitted under conditions. Commercial use requires a
 * separate license. Commercial licensing inquiries:
 * https://codeberg.org/Doul09/TaskMate/issues
 *
 * Powered by TaskMate, (c) 2026 PRADERE Sebastien
 */

/**
 * @file modules.c
 * @brief sysCore modules implementation.
 */

#include "sysCore/modules.h"

#include <stddef.h>

#include "hal/public/hal_context.h"
#include "hal/public/hal_i2c.h"
#include "hal/public/hal_lcd_AMC2004.h"
#include "hal/public/hal_rtc_ZS042.h"
#include "hal/public/hal_timerSTC.h"
#include "hal/public/hal_timerSched.h"
#include "hal/public/hal_usart.h"
#include "sysCore/auto_threads_list.h"
#include "tm_libc/tm_string.h"
#include "tm_libc/tm_syslog.h"

static struct
{
	mod_driver_item_t drivers[MOD_DRIVER_COUNT];
	mod_thread_item_t threads[MOD_THREAD_COUNT];
	uint8_t thread_current;
} mod_data_base;

void mod_threadSetCurrent(uint8_t n) { mod_data_base.thread_current = n; }
uint8_t mod_threadGetCurrent(void) { return mod_data_base.thread_current; }

void mod_threadSetSTC(uint16_t count)
{
	mod_data_base.threads[mod_data_base.thread_current].software_time_counter = count;
}

uint16_t mod_threadGetSTC(void)
{
	return mod_data_base.threads[mod_data_base.thread_current].software_time_counter;
	// return 1;
}

mod_driver_item_t *mod_driverGetPointer(uint8_t id) { return &mod_data_base.drivers[id]; }
mod_thread_item_t *mod_threadGetPointer(uint8_t id) { return &mod_data_base.threads[id]; }

// NOLINTBEGIN
// NOLINT(readability-magic-numbers)

void mod_threadsAlloc(void)
{
	tm_syslog(TM_STR("[modules.c] offsetof(name)                  = %i\n"),
			  (unsigned)offsetof(mod_thread_item_t, name));
	tm_syslog(TM_STR("[modules.c] offsetof(status)                = %i\n"),
			  (unsigned)offsetof(mod_thread_item_t, status));
	tm_syslog(TM_STR("[modules.c] offsetof(main)                  = %i\n"),
			  (unsigned)offsetof(mod_thread_item_t, main));
	tm_syslog(TM_STR("[modules.c] offsetof(software_time_counter) = %i\n"),
			  (unsigned)offsetof(mod_thread_item_t, software_time_counter));
	tm_syslog(TM_STR("[modules.c] offsetof(stack_pointer)         = %i\n"),
			  (unsigned)offsetof(mod_thread_item_t, stack_pointer));
	tm_syslog(TM_STR("[modules.c] offsetof(canary_low)            = %i\n"),
			  (unsigned)offsetof(mod_thread_item_t, canary_low));
	tm_syslog(TM_STR("[modules.c] offsetof(stack)                 = %i\n"),
			  (unsigned)offsetof(mod_thread_item_t, stack));
	tm_syslog(TM_STR("[modules.c] offsetof(canary_high)           = %i\n"),
			  (unsigned)offsetof(mod_thread_item_t, canary_high));
	tm_syslog(TM_STR("[modules.c] sizeof(mod_thread_item_t)       = %i\n"),
			  (unsigned)sizeof(mod_thread_item_t));

	mod_thread_item_t *thread;

	for( uint8_t i = 0; i < MOD_THREAD_COUNT; i++ )
	{
		thread = mod_threadGetPointer(i);
		thread->canary_low = MOD_CANARY;
		thread->canary_high = MOD_CANARY;
	}

	// [autoCode_tag] threads alloc
	// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

	mod_thread_item_t *mod;

	mod = mod_threadGetPointer(0);

	hal_threadContextInit(msg, &(mod->stack_pointer), &(mod->stack[MOD_THREAD_STACK_SIZE - 1]));
	mod->software_time_counter = 0;
	TM_STR_ROM_NEW(thread0_name, "msg");
	mod->name = &thread0_name;
	mod->status = 19;
	mod->main = msg;

	mod = mod_threadGetPointer(1);

	hal_threadContextInit(scli, &(mod->stack_pointer), &(mod->stack[MOD_THREAD_STACK_SIZE - 1]));
	mod->software_time_counter = 0;
	TM_STR_ROM_NEW(thread1_name, "scli");
	mod->name = &thread1_name;
	mod->status = 19;
	mod->main = scli;

	mod = mod_threadGetPointer(2);

	hal_threadContextInit(task1, &(mod->stack_pointer), &(mod->stack[MOD_THREAD_STACK_SIZE - 1]));
	mod->software_time_counter = 0;
	TM_STR_ROM_NEW(thread2_name, "task1");
	mod->name = &thread2_name;
	mod->status = 12;
	mod->main = task1;

	mod = mod_threadGetPointer(3);

	hal_threadContextInit(task2, &(mod->stack_pointer), &(mod->stack[MOD_THREAD_STACK_SIZE - 1]));
	mod->software_time_counter = 0;
	TM_STR_ROM_NEW(thread3_name, "task2");
	mod->name = &thread3_name;
	mod->status = 12;
	mod->main = task2;
	// clang-format on
	// [/tag]
}

void mod_driversAlloc(void)
{
	// [autoCode_tag] drivers alloc
	// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

	mod_driver_item_t *mod;

	mod = mod_driverGetPointer(0);
	TM_STR_ROM_NEW(driver0_name, "hal_timerSched");
	*(mod) = (mod_driver_item_t)
	{
		.name = &driver0_name,
		.status = 1,
		.init = hal_timerSchedInit,
		.start = hal_timerSchedStart,
		.stop = hal_timerSchedStop
	};

	mod = mod_driverGetPointer(1);
	TM_STR_ROM_NEW(driver1_name, "hal_timerSTC");
	*(mod) = (mod_driver_item_t)
	{
		.name = &driver1_name,
		.status = 1,
		.init = hal_timerSTCInit,
		.start = hal_timerSTCStart,
		.stop = hal_timerSTCStop
	};

	mod = mod_driverGetPointer(2);
	TM_STR_ROM_NEW(driver2_name, "hal_i2c");
	*(mod) = (mod_driver_item_t)
	{
		.name = &driver2_name,
		.status = 1,
		.init = hal_i2cInit,
		.start = hal_i2cStart,
		.stop = hal_i2cStop
	};

	mod = mod_driverGetPointer(3);
	TM_STR_ROM_NEW(driver3_name, "hal_usart");
	*(mod) = (mod_driver_item_t)
	{
		.name = &driver3_name,
		.status = 1,
		.init = hal_usartInit,
		.start = hal_usartStart,
		.stop = hal_usartStop
	};

	mod = mod_driverGetPointer(4);
	TM_STR_ROM_NEW(driver4_name, "hal_lcd");
	*(mod) = (mod_driver_item_t)
	{
		.name = &driver4_name,
		.status = 2,
		.init = hal_lcdInit,
		.start = hal_lcdStart,
		.stop = hal_lcdStop
	};

	mod = mod_driverGetPointer(5);
	TM_STR_ROM_NEW(driver5_name, "hal_rtc");
	*(mod) = (mod_driver_item_t)
	{
		.name = &driver5_name,
		.status = 2,
		.init = hal_rtcInit,
		.start = hal_rtcStart,
		.stop = hal_rtcStop
	};
	// clang-format on
	// [/tag]
}

// NOLINTEND
