/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file modules_list.h
 * @brief modules list
 */

#ifndef MODULES_LIST_H
#define MODULES_LIST_H

#if !defined(TM_SYSTEM_CRITICAL_ALLOWED)
	#error "NOT ALLOWED INCLUDE : modules_list.h"
#endif

// [autoCode_tag] modules list
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */



// clang-format on
// [/tag]

#endif
