/*
 * TaskMate Project
 * (c) 2025 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the TaskMate License
 * v1.0. See the LICENSE file for full license terms.
 *
 * Non-commercial use permitted under conditions. Commercial use requires a
 * separate license. Commercial licensing inquiries:
 * https://codeberg.org/Doul09/TaskMate/issues
 *
 * Powered by TaskMate, (c) 2025 PRADERE Sebastien
 */

/**
 * @file runLevel.h
 * @brief run level header
 *
 */

#ifndef RUNLEVEL_H
#define RUNLEVEL_H

#include <stdint.h>

// run levels definitions
#define RUN_NONE 0
#define RUN_CORE 1
#define RUN_DRIVER 2
#define RUN_SERVICE 3
#define RUN_USER 4

#define RUN_LEVEL_MASK 0x07
#define RUN_LEVEL_COUNT 5

// [autoCode_tag] run_levels define
// clang-format off
// why ? Auto-generated code

/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

#define RUN_LEVEL0_THREADS_COUNT 0
#define RUN_LEVEL1_THREADS_COUNT 0
#define RUN_LEVEL2_THREADS_COUNT 0
#define RUN_LEVEL3_THREADS_COUNT 2
#define RUN_LEVEL4_THREADS_COUNT 4

typedef struct
{
	uint8_t level0[RUN_LEVEL0_THREADS_COUNT + 1];
	uint8_t level1[RUN_LEVEL1_THREADS_COUNT + 1];
	uint8_t level2[RUN_LEVEL2_THREADS_COUNT + 1];
	uint8_t level3[RUN_LEVEL3_THREADS_COUNT + 1];
	uint8_t level4[RUN_LEVEL4_THREADS_COUNT + 1];
	uint8_t *levels[5];
	uint8_t current;
	uint8_t next;
} rl_data_base_t;

// clang-format on
// [/tag]

void rl_Alloc(void);

#endif
