/*
 * TaskMate Project
 * (c) 2025 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the TaskMate License
 * v1.0. See the LICENSE file for full license terms.
 *
 * Non-commercial use permitted under conditions. Commercial use requires a
 * separate license. Commercial licensing inquiries:
 * https://codeberg.org/Doul09/TaskMate/issues
 *
 * Powered by TaskMate, (c) 2025 PRADERE Sebastien
 */

/**
 * @file runLevel.c
 * @brief run level code
 *
 */

#include "sysCore/runLevel.h"

static rl_data_base_t to_run;

// NOLINTBEGIN
// NOLINT(readability-magic-numbers)

void rl_Alloc(void)
{

	// [autoCode_tag] run_levels alloc
// clang-format off
// why ? Auto-generated code

/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

	to_run = (rl_data_base_t){
		.level0 = {0},
		.level1 = {0},
		.level2 = {0},
		.level3 = {2,0,1},
		.level4 = {4,0,1,2,3},
		.levels = {to_run.level0, to_run.level1, to_run.level2, to_run.level3, to_run.level4}
	};
	to_run.current=RUN_CORE;
	to_run.next=RUN_CORE;
// clang-format on
	// [/tag]
}

// NOLINTEND
