/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the TaskMate License
 * v1.0. See the LICENSE file for full license terms.
 *
 * Non-commercial use permitted under conditions. Commercial use requires a
 * separate license. Commercial licensing inquiries:
 * https://codeberg.org/Doul09/TaskMate/issues
 *
 * Powered by TaskMate, (c) 2026 PRADERE Sebastien
 */

/**
 * @file error.c
 * @brief System wide error implementation
 *
 * @TODO Timeout routine, critical/fatal errors handling
 */

#include "sysCall/auto_error.h"

#include "hal/auto_hal_tmlibc.h"

// [autoCode_tag] error catalog
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

TM_STR_ROM_NEW(err0, "No error");
TM_STR_ROM_NEW(err1, "hal USART TX buffer empty");
TM_STR_ROM_NEW(err2, "hal USART RX buffer empty");
TM_STR_ROM_NEW(err3, "hal USART TX buffer full");
TM_STR_ROM_NEW(err4, "hal USART RX buffer full");
TM_STR_ROM_NEW(err5, "msg no more free channels");

const err_item_t error_catalog[] = 
{
	{err0, 1},
	{err1, 1},
	{err2, 1},
	{err3, 1},
	{err4, 1},
	{err5, 1},
};
// clang-format on
// [/tag]
