/*
 * TaskMate Project
 * (c) 2025 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the TaskMate License
 * v1.0. See the LICENSE file for full license terms.
 *
 * Non-commercial use permitted under conditions. Commercial use requires a
 * separate license. Commercial licensing inquiries:
 * https://codeberg.org/Doul09/TaskMate/issues
 *
 * Powered by TaskMate, (c) 2025 PRADERE Sebastien
 */

/**
 * @file error.c
 * @brief System wide error implementation
 *
 * @TODO Timeout routine, critical/fatal errors handling
 */

#include "sysCall/auto_error.h"

// [autoCode_tag] error catalog
// clang-format off
// why ? Auto-generated code

/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

const err_item_t error_catalog[] = 
{
	{"No error", 1},
	{"hal USART TX buffer empty", 1},
	{"hal USART RX buffer empty", 1},
	{"hal USART TX buffer full", 1},
	{"hal USART RX buffer full", 1},
	{"msg no more free channels", 1}
};
// clang-format on
// [/tag]
