/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the TaskMate License
 * v1.0. See the LICENSE file for full license terms.
 *
 * Non-commercial use permitted under conditions. Commercial use requires a
 * separate license. Commercial licensing inquiries:
 * https://codeberg.org/Doul09/TaskMate/issues
 *
 * Powered by TaskMate, (c) 2026 PRADERE Sebastien
 */

/**
 * @file error.c
 * @brief System wide error implementation
 *
 */

#include "sysCall/error.h"

#include "tm_libc/tm_string.h"

// [autoCode_tag] error catalog
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

TM_STR_ROM_NEW(err0, "No error");
TM_STR_ROM_NEW(err1, "Pointer is NULL");
TM_STR_ROM_NEW(err2, "Most useless error in the world");
TM_STR_ROM_NEW(err3, "Second most useless error");
TM_STR_ROM_NEW(err4, "hal USART TX buffer empty");
TM_STR_ROM_NEW(err5, "hal USART RX buffer empty");
TM_STR_ROM_NEW(err6, "hal USART TX buffer full");
TM_STR_ROM_NEW(err7, "hal USART RX buffer full");
TM_STR_ROM_NEW(err8, "msg no more free channels");

const err_item_t error_catalog[] = 
{
	{&err0, 1},
	{&err1, 1},
	{&err2, 1},
	{&err3, 1},
	{&err4, 1},
	{&err5, 1},
	{&err6, 1},
	{&err7, 1},
	{&err8, 1},
};
// clang-format on
// [/tag]

const tm_string_t *err_getMessage(uint8_t num)
{
	if( num < ERROR_COUNT)
	{
		return error_catalog[num].name;
	}
	return 0;
}
