/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the TaskMate License
 * v1.0. See the LICENSE file for full license terms.
 *
 * Non-commercial use permitted under conditions. Commercial use requires a
 * separate license. Commercial licensing inquiries:
 * https://codeberg.org/Doul09/TaskMate/issues
 *
 * Powered by TaskMate, (c) 2026 PRADERE Sebastien
 */

/**
 * @file sysCall.c
 * @brief Implements system calls.
 *
 * @warning This file contains ATOMIC material !
 *
 */

#include "sysCall/sysCall.h"

#include <util/atomic.h>

#include "hal/auto_hal_system.h"
#include "hal/auto_hal_user.h"
#include "sysCore/modules.h"
#include "tm_libc/tm_string.h"

static uint8_t system_status = 0;

// [autoCode_tag] system info
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

TM_STR_ROM_NEW(tm_ver, "0.26");
const uint16_t tm_build = 4558;
TM_STR_ROM_NEW(arch_name, "avr8");
TM_STR_ROM_NEW(mcu_name, "atmega2560");
TM_STR_ROM_NEW(board_name, "arduinoMega");

// clang-format on
// [/tag]

static const sc_info_t info = {.tm_ver = &tm_ver,
							   .tm_build = tm_build,
							   .arch = &arch_name,
							   .mcu = &mcu_name,
							   .board = &board_name};

void sc_targetGetInfo(const sc_info_t **dest) { *dest = &info; }

void sc_threadSetSTC(uint16_t count)
{
	ATOMIC_BLOCK(ATOMIC_FORCEON) { mod_threadSetSTC(count); }
}

uint16_t sc_threadGetSTC(void)
{
	ATOMIC_BLOCK(ATOMIC_FORCEON) { return mod_threadGetSTC(); }
	return 0; // dummy return to avoid -Wno-return-type
}

void sc_handYield(void) { hal_timerSchedulerLoad(); }

void sc_flagClear(uint8_t flag) { system_status &= ~flag; }
void sc_flagSet(uint8_t flag) { system_status |= flag; }
uint8_t sc_flagGet(uint8_t flag) { return system_status &= flag; }
