/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file error_catalog.h
 * @brief error catalog
 */

#ifndef INTERFACES_ERROR_CATALOG_H
#define INTERFACES_ERROR_CATALOG_H

typedef enum
{
	ERROR_LOW,
	ERROR_MID,
	ERROR_HIGH
} err_critical_t;

// [autoCode_tag] error_enum
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

typedef enum
{
	ERR_HAL_USART_TX_BUFFER_EMPTY,
	ERR_HAL_USART_RX_BUFFER_EMPTY,
	ERR_HAL_USART_TX_BUFFER_FULL,
	ERR_HAL_USART_RX_BUFFER_FULL,
	ERR_NO_ERROR,
	ERR_NULL_POINTER,
	ERR_UNKNOW,
	ERR_RUNTIME,
	ERR_MSG_OUT_OF_FREE_CHANNEL,
	ERROR_COUNT
} err_codes_t;


// clang-format on
// [/tag]

#endif // INTERFACES_ERROR_CATALOG_H
