/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file error_catalog.h
 * @brief error catalog header declarations.
 */

#ifndef INTERFACES_ERROR_CATALOG_H
#define INTERFACES_ERROR_CATALOG_H

#include "interfaces/error_level.h"

// [autoCode_tag] error_enum
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

typedef enum
{
	ERR_HAL_LCD_CURSOR_OUT_OF_RANGE,
	ERR_HAL_RTC_TIME_OUT_OF_RANGE,
	ERR_HAL_I2C_START_FAILED,
	ERR_HAL_I2C_ADDRESS_NACK,
	ERR_HAL_I2C_WRITE_FAILED,
	ERR_HAL_I2C_READ_FAILED,
	ERR_HAL_I2C_SCAN_COMPLETE,
	ERR_HAL_USART_TX_BUFFER_EMPTY,
	ERR_HAL_USART_RX_BUFFER_EMPTY,
	ERR_HAL_USART_TX_BUFFER_FULL,
	ERR_HAL_USART_RX_BUFFER_FULL,
	ERR_NO_ERROR,
	ERR_NULL_POINTER,
	ERR_I2C_SCAN_ADDRESS_BUFFER_FULL,
	ERR_UNKNOWN,
	ERR_RUNTIME,
	ERR_HAL_DRIVER_INVALID_CONTROL,
	ERR_HAL_DRIVER_INVALID_VALUE,
	ERR_HAL_DRIVER_INVALID_STATE,
	ERR_HAL_DRIVER_NOT_INITIALIZED,
	ERR_HAL_DRIVER_NOT_RUNNING,
	ERR_HAL_DRIVER_DEAD,
	ERR_HAL_DRIVER_DEPENDENCY,
	ERROR_COUNT
} err_codes_t;


// clang-format on
// [/tag]

#endif // INTERFACES_ERROR_CATALOG_H
