/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file gpio_signals.h
 * @brief gpio signals header declarations.
 *
 */

#ifndef INTERFACES_GPIO_SIGNALS_H
#define INTERFACES_GPIO_SIGNALS_H

// [autoCode_tag] gpio_signals
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

typedef enum
{
	GPIO_SIGNAL_INBOARD_LED,
	GPIO_SIGNAL_TASK1_LED,
	GPIO_SIGNAL_TASK2_LED,
	GPIO_SIGNAL_COUNT
} gpio_signal_t;

// clang-format on
// [/tag]

#endif // INTERFACES_GPIO_SIGNALS_H
