/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file modules_define.h
 * @brief modules define header declarations.
 */

#ifndef INTERFACES_MODULES_DEFINE_H
#define INTERFACES_MODULES_DEFINE_H

#include <stdbool.h>
#include <stdint.h>

#include "interfaces/error_catalog.h"

// [autoCode_tag] modules_count
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

#define TM_MOD_DRIVER_COUNT 6
#define TM_MOD_THREAD_COUNT 4

// clang-format on
// [/tag]

// Definitions for autoCode
#define TM_MOD_COUNT_MAX 256

#define TM_MOD_DRIVER_ID 0
#define TM_MOD_THREAD_ID 1
#define TM_MOD_THREAD_SYS_ID 2
#define TM_MOD_THREAD_USER_ID 3

#define TM_MOD_TYPE_COUNT 2
#define TM_MOD_NAME_SIZE_MAX 32
#define TM_MOD_I2C_ADDRESS_MAX 0x7Eu
#define TM_MOD_I2C_ADDRESS_NONE 0xFFu

// System
#define TM_MOD_THREAD_STACK_SIZE 256

// driver control
typedef enum
{
	DRV_CTRL_INIT,
	DRV_CTRL_START,
	DRV_CTRL_STOP,
	DRV_CTRL_RLSET,
	DRV_CTRL_RLGET,
	DRV_CTRL_SETBIT,
	DRV_CTRL_CLEARBIT,
	DRV_CTRL_GETBIT,
	DRV_CTRL_GETSTATUS,
	DRV_CTRL_GETLASTERROR,
	DRV_CTRL_SCAN
} hal_driver_control_t;

// Driver status bits
typedef uint8_t hal_driver_status_t;

// bits [2:0] contain the run level
typedef enum
{
	DRV_BIT_INIT = 3,
	DRV_BIT_START,
	DRV_BIT_ERROR,
	DRV_BIT_DEAD
} hal_driver_status_bit_t;

// driver status
typedef enum
{
	DRV_STATE_OFF,
	DRV_STATE_INITIALIZED,
	DRV_STATE_RUNNING,
	DRV_STATE_ERROR,
	DRV_STATE_DEAD
} hal_driver_state_t;

typedef union
{
	uint8_t run_level;
	hal_driver_status_bit_t status_bit;
	bool bit_value;
	err_codes_t error;
	uint8_t i2c_address;
} hal_driver_control_data_t;

// Thread status bits
// Bits [2:0] contain the run level
#define TM_MOD_THREAD_TYPE_USER 3
#define TM_MOD_THREAD_TYPE_SYS 4
#define TM_MOD_THREAD_DEAD 5
#define TM_MOD_THREAD_YIELDED 6

#endif // INTERFACES_MODULES_DEFINE_H
