/*
 * TaskMate Project
 * (c) 2026 PRADERE Sebastien
 *
 * This file is part of TaskMate and is distributed under the BSD-2-Clause License.
 * See the LICENSE file for full license terms.
 */

/**
 * @file modules_define.h
 * @brief modules define header declarations.
 */

#ifndef INTERFACES_MODULES_DEFINE_H
#define INTERFACES_MODULES_DEFINE_H

#include <stdint.h>

// [autoCode_tag] modules_count
// clang-format off
/*
 * do not edit code between tag
 * code generated by autoCode, any change will be lost
 */

#define TM_MOD_DRIVER_COUNT 6
#define TM_MOD_THREAD_COUNT 4

// clang-format on
// [/tag]

// Definitions for autoCode
#define TM_MOD_COUNT_MAX 256

#define TM_MOD_DRIVERS_ID 0
#define TM_MOD_THREAD_ID 1
#define TM_MOD_THREAD_SYS_ID 2
#define TM_MOD_THREAD_USER_ID 3

#define TM_MOD_TYPE_COUNT 2
#define TM_MOD_NAME_SIZE_MAX 32

// System
#define TM_MOD_THREAD_STACK_SIZE 256

// Driver control
#define DRV_CTRL_INIT 1
#define DRV_CTRL_START 2
#define DRV_CTRL_STOP 3
#define DRV_CTRL_RLSET 4
#define DRV_CTRL_RLGET 5
#define DRV_CTRL_SETBIT 6
#define DRV_CTRL_CLEARBIT 7
#define DRV_CTRL_GETBIT 8
#define DRV_CTRL_GETSTATUS 9
#define DRV_UNKNOW 99

// Driver status bits
typedef uint8_t hal_driver_status_t;

// Bits [2:0] contain the run level
#define DRV_BIT_INIT 3
#define DRV_BIT_START 4
#define DRV_BIT_ERROR 5
#define DRV_BIT_DEAD 6

// Driver status
#define DRV_STATE_OFF 1
#define DRV_STATE_INITIALIZED 2
#define DRV_STATE_RUNNING 3
#define DRV_STATE_ERROR 4

// Thread status bits
// Bits [2:0] contain the run level
#define TM_MOD_THREAD_TYPE_USER 3
#define TM_MOD_THREAD_TYPE_SYS 4
#define TM_MOD_THREAD_DEAD 5
#define TM_MOD_THREAD_YIELDED 6

#endif // INTERFACES_MODULES_DEFINE_H
